on:
  workflow_dispatch:
  push:
    branches:
      - main
      
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t waivedinsocket:latest .
            docker tag waivedinsocket:latest waivedinsocket.azurecr.io/waivedin-socket:${{ github.sha }}
            docker push waivedinsocket.azurecr.io/waivedin-socket:${{ github.sha }}
         
      # Pull the image from Azure Container Registry
        - name: 'Pull image'
          run: |
            docker pull waivedinsocket.azurecr.io/waivedin-socket:${{ github.sha }}

      # Run the image
        - name: 'Run Docker container'
          run: |
            docker run -d -p 3000:3000 waivedinsocket.azurecr.io/waivedin-socket:${{ github.sha }} 
        
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.STAGING_SSH_HOST }}
           username: ${{ secrets.STAGING_SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
